# -*- coding: utf-8 -*-
"""simulador_poupanca.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zNMgsASn3MViwYZ13vG0Ot3kcQ8TWf-b
"""

def simulador_poupanca():

  saldo = float(input("Valor inicial do investimento: "))

  taxa = float(input("Taxa de juros mensal (em %): "))

  meses = int(input("Número de meses da simulação: "))



  for m in range(1, meses + 1):

    aporte = float(input(f"Quanto deseja depositar no mês {m}? (0 para nenhum): "))



    saldo += aporte

    juros = saldo * (taxa / 100)

    saldo += juros



    print(f"Mês {m}: Saldo atualizado = R$ {saldo:.2f}")



    if saldo > 10000.0:

      print(f"Parabéns! Você atingiu a meta de 10k no mês {m}")



  print(f"\nResultado final após {meses} meses: R$ {saldo:.2f}")





simulador_poupanca()